### ISSUE TITLE
Add support for OIDC

### ISSUE THREAD

**Issue by Sahil91** [Aguafrommars/DynamicAuthProviders#134]
To meet my requirements, I need to configure multiple OIDC providers within the Identity Server. Each OIDC provider has a different authority URL, which we need to configure from the database. It would be great if you could provide examples on how to achieve this, or we can include this in the current code.

**Comment by Sahil91** [comment]
![image](https://user-images.githubusercontent.com/17924891/156576562-79a62263-5857-4da2-9d9e-e350fbcf9e09.png)

In the image, Authority URL is dynamic and in the database, scheme column is  primary key. Multiple OIDCs cannot be added with different authorities. In spite of removing the primary key from scheme column, it overrides the previous record added for oidc. 

While TheldServer perfectly fits my requirements, I cannot use TheldServer because I need my own implementation of an identity server.

**Comment by aguacongas** [comment]
`CallbackPath` must be unique or it doesn't work because the authentication middleware find the provider with the `CallbackPath`. `Scheme` must be unique too, it's why it's the key.
